### ISSUE TITLE
Incompatible with SRParasites-1.9.9

### ISSUE THREAD

**Issue by HuangAdam** [fonnymunkey/RLCombat#5]
It makes player cannot attack other player and spam.
Only three mods: 
- ReachFix-1.0.8
- RLCombat-2.0.7
- SRParasites-1.9.9

Error text:
```
[19:45:13] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingHurtEvent@393611de:
java.lang.NullPointerException: null
        at com.dhanantry.scapeandrunparasites.util.handlers.SRPEventHandlerBus.entityHurt(SRPEventHandlerBus.java:369) ~[SRPEventHandlerBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_SRPEventHandlerBus_entityHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604) ~[ForgeHooks.class:14.23.5.2860]
        at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1120) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) ~[oq.class:?]
        at bettercombat.mod.util.Helpers.attackTargetEntityItem(Helpers.java:286) ~[Helpers.class:2.0.7]
        at bettercombat.mod.network.PacketMainhandAttack$Handler.handle(PacketMainhandAttack.java:72) ~[PacketMainhandAttack$Handler.class:2.0.7]
        at bettercombat.mod.network.PacketMainhandAttack$Handler.lambda$onMessage$0(PacketMainhandAttack.java:61) ~[PacketMainhandAttack$Handler.class:2.0.7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_361]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_361]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]
[19:45:13] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[19:45:13] [Server thread/ERROR] [FML]: 0: NORMAL
[19:45:13] [Server thread/ERROR] [FML]: 1: ASM: com.dhanantry.scapeandrunparasites.util.handlers.SRPEventHandlerBus@443bf3e4 entityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
[19:45:13] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_361]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_361]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]
Caused by: java.lang.NullPointerException
        at com.dhanantry.scapeandrunparasites.util.handlers.SRPEventHandlerBus.entityHurt(SRPEventHandlerBus.java:369) ~[SRPEventHandlerBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_SRPEventHandlerBus_entityHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604) ~[ForgeHooks.class:14.23.5.2860]
        at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1120) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) ~[oq.class:?]
        at bettercombat.mod.util.Helpers.attackTargetEntityItem(Helpers.java:286) ~[Helpers.class:2.0.7]
        at bettercombat.mod.network.PacketMainhandAttack$Handler.handle(PacketMainhandAttack.java:72) ~[PacketMainhandAttack$Handler.class:2.0.7]
        at bettercombat.mod.network.PacketMainhandAttack$Handler.lambda$onMessage$0(PacketMainhandAttack.java:61) ~[PacketMainhandAttack$Handler.class:2.0.7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_361]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_361]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by fonnymunkey** [comment]
I don't know how/if this is being caused by RLCombat itself, and not just a bug in SRParasites itself, since I can't tell exact where it is crashing, however RLMixins (https://www.curseforge.com/minecraft/mc-mods/rlmixins) has some patches to SRParasites, that will hopefully just be fixed in the next SRParasites update itself.

**Comment by HuangAdam** [comment]
Thanks for reply and remind.
It is a [known bug](https://www.curseforge.com/minecraft/mc-mods/scape-and-run-parasites/issues/242), the next version would be fixed.
